package com.example.airline_api.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;


@Entity //Represents a table in a relational database
@Table(name = "Passenger")
public class Passenger {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Specifies that the primary key values for instances of Passenger will be generated by the database
    // using an auto-increment column.
    @Column
    private long id;
    @Column
    private String name;
    @Column
    private String email;

    @ManyToMany //indicates a many-to-many relationship between Passenger and the entity Flight
    @JoinTable( //define the details of the join table that will be used to manage the many-to-many relationship.
            name = "passengers_flights", //Specifies the name of the join table as "passengers_flights.
            joinColumns = @JoinColumn(name = "passenger_id"),
            inverseJoinColumns = @JoinColumn(name = "flight_id")
    )
    @JsonIgnoreProperties({"passengers"})
    //This is used to ignore the "passengers" properties when serializing to JSOn to prevent recursion
    private List<Flight> flights;

    public Passenger(String name, String email) {
        this.name = name;
        this.email = email;
        this.flights = new ArrayList<>();
    }

    public Passenger() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public List<Flight> getFlights() {
        return flights;
    }

    public void setFlights(List<Flight> flights) {
        this.flights = flights;
    }
}
